version: "3"

services:
  app: &app
    build:
      context: .
      dockerfile: ./.dockerdev/Dockerfile
      args:
        RUBY_VERSION: "3.0.2"
    image: benchmark:0.0.1
    tmpfs: /tmp

  runner:
    <<: *app
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
      - bundle:/bundle
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432
    depends_on:
      - postgres
    command: /bin/ash
    ports:
      - "3000:3000"
      - "3002:3002"

  postgres:
    image: postgres:14.0-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
  bundle:
